version: 2.1

jobs:
  build:
    docker:
      - image: buildpack-deps:eoan
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apt update && apt install -y cmake
      - run:
          name: Build
          command: |
            mkdir build && cd build
            cmake ..
            make

workflows:
  build:
    jobs:
      - build
