version: 2.1

jobs:
  build:
    docker:
      - image: buildpack-deps:eoan
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Hello
          command: echo "Hello"

workflows:
  build:
    jobs:
      - build
